2.0.13 - perlcritic-severity, conditional man pages, see ChangeLog

diff --git a/resources/install-from-cpan.in b/resources/install-from-cpan.in
--- a/resources/install-from-cpan.in
+++ b/resources/install-from-cpan.in
@@ -1,14 +1,36 @@
 #!/usr/bin/env bash
 #-*- mode: sh; -*-
+# 
+# version: @PACKAGE_VERSION@
+# project: @PACKAGE_NAME@
+
+requires="$1"
+
+if test -z "$requires"; then
+   >&2 echo "usage: install-from-cpan requires.txt"
+   exit 1;
+fi
+
+if ! test -e "$requires"; then
+   >&2 echo "$requires not found"
+   exit 1;
+fi
+
 set -ex
 
 destdir=@bindir@
 logdir=@localstatedir@/log
 
-curl -L https://cpanmin.us -o ${destdir}/cpanm
-chmod +x ${destdir}/cpanm
+cpanm=$(command -v cpanm)
 
-for a in $(cat @datadir@/@PACKAGE@/requires.txt | awk '{print $1}'); do
+if test -z "$cpanm"; then
+    curl -L https://cpanmin.us -o ${destdir}/cpanm
+    chmod +x ${destdir}/cpanm
+fi
+
+set -o pipefail
+
+for a in $(cat $requires | awk '{print $1}'); do
   ${destdir}/cpanm -n -v $a | tee -a ${logdir}/cpanm-install.log;
 done
 
